# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gpio/gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio || ORIG_REF_NAME==gpio} -quiet] -quiet

# IP: bd/gpio/ip/gpio_processing_system7_0_0/gpio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_processing_system7_0_0 || ORIG_REF_NAME==gpio_processing_system7_0_0} -quiet] -quiet

# XDC: bd/gpio/gpio_ooc.xdc
